import { chmod, mkdir, rename, unlink, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { join } from "node:path";
import { normalizePublicBaseUrl, normalizeS3Endpoint } from "./config.mjs";
import {
  AUTO_SUBMIT_KEY,
  CONFIG_FILENAME,
  DEFAULT_S3_REGION,
  HSC_S3_KEYS,
  HSC_S3_NAMESPACE,
  HSC_S3_PREFIX,
  S3_KEYS,
  S3_NAMESPACE,
} from "./config-schema.mjs";

export const PROVIDER_PRESETS = {
  aws: { region: DEFAULT_S3_REGION, endpoint: "", forcePathStyle: false },
  r2: { region: "auto", endpoint: "https://{accountId}.r2.cloudflarestorage.com", forcePathStyle: false },
  minio: { region: DEFAULT_S3_REGION, endpoint: "http://localhost:9000", forcePathStyle: true },
  generic: { region: DEFAULT_S3_REGION, endpoint: "", forcePathStyle: false },
};

export function providerFieldDefault(existing, provider, field, overrides = {}) {
  const providerPreset = PROVIDER_PRESETS[provider];
  if (!providerPreset) throw new Error(`Unknown S3 provider: ${provider}`);

  const preset = { ...providerPreset, ...overrides };
  if (!Object.hasOwn(preset, field)) {
    throw new Error(`Unknown ${provider} provider field: ${field}`);
  }
  return provider === existing.provider ? existing[field] || preset[field] : preset[field];
}

export function validateEndpointInput(value, accountId) {
  try {
    normalizeS3Endpoint(value, accountId, "S3 endpoint", "Account ID");
    return true;
  } catch (error) {
    return `${error.message} Example: https://s3.provider.example`;
  }
}

export function validatePublicBaseUrlInput(value) {
  try {
    normalizePublicBaseUrl(value, "Public base URL");
    return true;
  } catch (error) {
    return `${error.message} Example: https://img.example.com`;
  }
}

export function setupInitialValues(fileEnv = {}) {
  const hasHscNamespace = Object.keys(fileEnv).some((key) => key.startsWith(HSC_S3_PREFIX));
  const keys = hasHscNamespace ? HSC_S3_KEYS : S3_KEYS;
  const values = {};

  for (const [field, key] of Object.entries(keys)) {
    values[field] = typeof fileEnv[key] === "string" ? fileEnv[key] : "";
  }

  values.autoSubmit = fileEnv[AUTO_SUBMIT_KEY] || "false";
  values.provider = inferProvider(values);
  values.sourceNamespace = hasHscNamespace ? HSC_S3_NAMESPACE : S3_NAMESPACE;
  return values;
}

export function buildSetupEnv(values) {
  const result = {};

  for (const [field, key] of Object.entries(HSC_S3_KEYS)) {
    const value = values[field];
    if (value !== undefined && value !== null && String(value).trim() !== "") {
      result[key] = String(value).trim();
    }
  }

  result[HSC_S3_KEYS.forcePathStyle] = String(Boolean(values.forcePathStyle));
  result[AUTO_SUBMIT_KEY] = String(Boolean(values.autoSubmit));
  return result;
}

export function serializeSetupEnv(values) {
  const groups = [
    ["# Generated by the Herdr S3 Image Publisher interactive setup.", [
      HSC_S3_KEYS.accountId,
      HSC_S3_KEYS.endpoint,
      HSC_S3_KEYS.region,
      HSC_S3_KEYS.bucket,
      HSC_S3_KEYS.accessKeyId,
      HSC_S3_KEYS.secretAccessKey,
      HSC_S3_KEYS.sessionToken,
    ]],
    ["# URL generation", [
      HSC_S3_KEYS.urlMode,
      HSC_S3_KEYS.presignExpiresIn,
      HSC_S3_KEYS.publicBaseUrl,
    ]],
    ["# Upload behavior", [
      HSC_S3_KEYS.keyPrefix,
      HSC_S3_KEYS.forcePathStyle,
      HSC_S3_KEYS.cacheControl,
      AUTO_SUBMIT_KEY,
    ]],
  ];

  const lines = [];
  for (const [heading, keys] of groups) {
    const entries = keys.filter((key) => Object.hasOwn(values, key));
    if (entries.length === 0) continue;
    if (lines.length > 0) lines.push("");
    lines.push(heading);
    for (const key of entries) lines.push(`${key}=${quoteEnvValue(values[key])}`);
  }
  return `${lines.join("\n")}\n`;
}

export async function writeSetupEnv({ configDir, values, platform = process.platform }) {
  if (!configDir) throw new Error("HERDR_PLUGIN_CONFIG_DIR is not set.");

  const target = join(configDir, CONFIG_FILENAME);
  const temporary = join(configDir, `${CONFIG_FILENAME}.${process.pid}.${randomUUID()}.tmp`);
  await mkdir(configDir, { recursive: true, mode: 0o700 });

  try {
    if (platform !== "win32") await chmod(configDir, 0o700);
    await writeFile(temporary, serializeSetupEnv(values), { encoding: "utf8", flag: "wx", mode: 0o600 });
    if (platform !== "win32") await chmod(temporary, 0o600);
    await rename(temporary, target);
    if (platform !== "win32") await chmod(target, 0o600);
  } catch (error) {
    await unlink(temporary).catch(() => {});
    throw error;
  }

  return target;
}

function inferProvider(values) {
  const endpoint = values.endpoint || "";
  if (!endpoint) return "aws";
  if (endpoint.includes("r2.cloudflarestorage.com")) return "r2";
  if (values.forcePathStyle?.toLowerCase() === "true") return "minio";
  return "generic";
}

function quoteEnvValue(value) {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}
